<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE EMPLOYEES [
	<!ELEMENT EMPLOYEES (EMPLOYEE)>
	<!ELEMENT EMPLOYEE (EMP_ID, EMP_NAME, COUNTRY, OFFICE)>
	<!ELEMENT EMP_ID    (#PCDATA)>
	<!ELEMENT EMP_NAME  (#PCDATA)>
	<!ELEMENT COUNTRY   (#PCDATA)>
	<!ELEMENT OFFICE    (#PCDATA)>
	<!ATTLIST OFFICE PHONE NMTOKEN #REQUIRED>
        <!ENTITY country "INDIA">
]>

<EMPLOYEES>
	<EMPLOYEE>
		<EMP_ID> 10001 </EMP_ID>
		<EMP_NAME> Atul Kahate </EMP_NAME>
		<COUNTRY> &country; </COUNTRY>
		<OFFICE PHONE="91-079-2689578"></OFFICE>
	</EMPLOYEE>
</EMPLOYEES>
