=== maahirgit/College/COLLEGE - 4/XML/Practical/UNIT_2/demo_6.dtd
<!ELEMENT BOOKS (BOOK*) >
<!ELEMENT BOOK (BOOK_TITLE, SUB_TITLE, AUTHOR+, PUB_YEAR) >
<!ELEMENT BOOK_TITLE (#PCDATA) >
<!ELEMENT SUB_TITLE EMPTY>
<!ELEMENT AUTHOR (#PCDATA) >
<!ELEMENT PUB_YEAR (#PCDATA | REPRINT)>
<!ELEMENT REPRINT (#PCDATA)>

=== maahirgit/College/COLLEGE - 4/XML/Practical/UNIT_2/DEMO_6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BOOKS SYSTEM "demo_6.dtd">

<BOOKS>
	<BOOK>
		<BOOK_TITLE> LOOK Homeward, Angle </BOOK_TITLE>
		<SUB_TITLE></SUB_TITLE>
		<AUTHOR>  Thomas </AUTHOR>
		<AUTHOR> Wolfe </AUTHOR>
		<PUB_YEAR>
			<REPRINT>2012</REPRINT>	
		</PUB_YEAR>
	</BOOK>	

	<BOOK>
		<BOOK_TITLE> Gravity's Rainbow </BOOK_TITLE>
		<SUB_TITLE></SUB_TITLE>
		<AUTHOR> Pyncon, Thomas </AUTHOR>
		<PUB_YEAR>2010
				<REPRINT>2012</REPRINT>
				<REPRINT>2014</REPRINT>
		</PUB_YEAR>
	</BOOK>		
</BOOKS>
