<?xml version="1.0"?>
<!DOCTYPE elective_sub [
<!ELEMENT elective_sub (Marksheet,EnrollmentNo,subject+,student+)>
<!ELEMENT Marksheet (#PCDATA)>
<!ELEMENT EnrollmentNo (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT student (#PCDATA)>
<!ATTLIST Marksheet result (PASS | FAIL) "PASS">
<!ATTLIST Enrollment format NMTOKENS #REQUIRED> 
<!ATTLIST subject sid ID #REQUIRED>
<!ATTLIST student stid IDREF #REQUIRED>
<!ENTITY nm "XML">
]>	
	<elective_sub>
		<sub>&nm;</sub>
		<Marksheet result="PASS">Congrat</Marksheet>
		<EnrollmentNo format="2022_1123-8988">AMit</EnrollmentNo>
		<subject sid="s1">Android</subject>
		<subject sid="s2">IOS</subject>
		
		<student stid="s1">Amit</student>
		<student stid="s2">Kishor</student>
		<student stid="s1">Atul</student>
		<Equa>&</Equa>
	
	</elective_sub>