=== maahirgit/College/COLLEGE - 4/XML/UNIT_4/emp.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="EMPLOYEE" type="EmpType"/>
		
		<xsd:complexType name="ProjectType">
			<xsd:sequence>
				<xsd:element name="NAME" type="xsd:string"/>
			</xsd:sequence>
		</xsd:complexType>
			
		<xsd:complexType name="SubordinateType">
			<xsd:sequence>
				<xsd:element name="NAME" type="xsd:string"/>
			</xsd:sequence>
		</xsd:complexType>

		<xsd:complexType name="EmpType">
			<xsd:sequence>
				<xsd:element name="NAME" type="xsd:string"/>
				<xsd:element name="PROJECT" type="ProjectType" maxOccurs="unbounded"/>
				<xsd:element name="SUBORDINATE" type="SubordinateType" maxOccurs="unbounded"/>
				<xsd:element name="DESIGNATION" type="xsd:integer"/>
				<xsd:element name="SALARY" type="xsd:integer"/>
			</xsd:sequence>
		</xsd:complexType>
</xsd:schema>

=== maahirgit/College/COLLEGE - 4/XML/UNIT_4/emp.xml
<?xml version="1.0" encoding="UTF-8"?>

<EMPLOYEE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="emp.xsd">

	<NAME> Medha Pranjape </NAME>
	
	<PROJECT>
		<NAME> Card Rewrite </NAME>	
	</PROJECT>
	<PROJECT>
		<NAME> Electronic Bill Payments </NAME>	
	</PROJECT>
	<PROJECT>
		<NAME> Work Flow Management </NAME>	
	</PROJECT>
	
	<SUBORDINATE>
		<NAME> Pankaj Patel </NAME>
	</SUBORDINATE>

	<DESIGNATION> Project Manager</DESIGNATION>
	<SALARY> 100000 </SALARY>	

</EMPLOYEE>
