=== maahirgit/College/COLLEGE - 4/XML/Unit - 2/four.dtd
<!ELEMENT Student (Student_Name,Personal_Info,Result)>
<!ELEMENT Student_Name (#PCDATA)>
<!ELEMENT Personal_Info (Address,BirthDate,Gender,Mobile)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT BirthDate (#PCDATA)>
<!ELEMENT Gender (Male|Female)>
<!ELEMENT Male (#PCDATA)>
<!ELEMENT Female (#PCDATA)>
<!ELEMENT Mobile (#PCDATA)>
<!ELEMENT Result (Total,Percentage,Grade)>
<!ELEMENT Total (#PCDATA)>
<!ELEMENT Percentage (#PCDATA)>
<!ELEMENT Grade (Pass|First|Dist|Second|Fail)>

=== maahirgit/College/COLLEGE - 4/XML/Unit - 2/four.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Student SYSTEM "four.dtd">
<Student>
	<Student_Name>Maahir</Student_Name>
	<Personal_Info>
		<Address>1st FF,xyz</Address>
		<BirthDate>01-01-2004</BirthDate>
		<Gender><Male>Yes<Female></Gender>
		<Mobile>9408758428</Mobile>
	</Personal_Info>
	<Result>
		<Total>100</Total>
		<Percentage>90%</Percentage>
		<Grade>Fail</Grade>
	</Result>
</Student>
