=== maahirgit/College/COLLEGE - 4/XML/Unit - 2/one.dtd
<!ELEMENT personal_info(id,name,address,mobile,dob,age,qualification)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT qualification (#PCDATA)>

=== maahirgit/College/COLLEGE - 4/XML/Unit - 2/one.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personal_info SYSTEM "one.dtd">
<personal_info>
    <roll_no>1</roll_no>
    <name>Maahir</name>
    <address>abc--</address>
    <mobile>7894561230</mobile>
    <dob>01/01/2001</dob>
    <age>20</age>
    <qualification>Bca</qualification>
</personal_info>
