=== maahirgit/College/COLLEGE - 4/XML/Unit - 2/six.dtd
<!ELEMENT Student (Name,ID,Plan)>
<!ELEMENT Name (fname,lname)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT Plan (courses)>
<!ELEMENT courses (course*)>
<!ATTLIST courses year CDATA #REQUIRED>
<!ELEMENT course (name,shortName,record*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT shortName (#PCDATA)>
<!ELEMENT record (Grade,date)>
<!ELEMENT Grade (#PCDATA)>
<!ELEMENT date (#PCDATA)>

=== maahirgit/College/COLLEGE - 4/XML/Unit - 2/six.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Student SYSTEM "six.dtd">
<Student>
	<Name>
		<fname>Maahir</fname>
		<lname>Shah</lname>
	</Name>
	<ID>101</ID>
	<Plan>
		<courses year="2022">
			<course>
				<name>Bca</name>
				<shortName>IT</shortName>
				<record>
					<Grade>A</Grade>
					<date>2023-05-15</date>
				</record>
			</course>
		</courses>
	</Plan>
</Student>

<!--* is used for zero or more times-->
