=== maahirgit/College/COLLEGE - 4/XML/Unit - 2/three.dtd
<!ELEMENT OrderDetail (Order_Detail+)>
<!ELEMENT Order_Detail (OrderNumber,OrderRate,OrderAmount,item+)>
<!ATTLIST Order_Detail orderdate CDATA #REQUIRED>
<!ELEMENT OrderNumber (#PCDATA)>
<!ELEMENT OrderRate (#PCDATA)>
<!ELEMENT OrderAmount (#PCDATA)>
<!ELEMENT item (ItemPrice*,ItemName?,Quantity*)>
<!ELEMENT ItemPrice (#PCDATA)>
<!ELEMENT ItemName+ (#PCDATA)>
<!ELEMENT Quantity (#PCDATA)>

=== maahirgit/College/COLLEGE - 4/XML/Unit - 2/three.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OrderDetail SYSTEM "three.dtd">
	<OrderDetail>
		<Order_Detail orderdate="10-10-2010">
			<OrderNumber>101</OrderNumber>
			<OrderRate>1000</OrderRate>
			<OrderAmount>10000</OrderAmount>
			<item>
				<ItemPrice>100</ItemPrice>
				<ItemName>abc</ItemName>
				<Quantity>100</Quantity>
			</item>
		</Order_Detail>
	</OrderDetail>
